https://github.com/debosama10/leechbot#variable-explanations
https://github.com/debosama10/leechbot#mandatory-variables

  - `TG_BOT_TOKEN`: 1948841770:AAGX5_t7-q0uodiq_U3XwI2qV7d80LFDASA
  - `APP_ID` 3495663
  - `API_HASH`: bd2c2a8c9fa3169038cdf3c9c8215f19
  - `AUTH_CHANNEL`: -1001585071628
  - `OWNER_ID`: 1874954413
- `LEECH_COMMAND`: /leech
  - `LEECH_UNZIP_COMMAND`: /extract
  - `LEECH_ZIP_COMMAND`:/archive
  - `YTDL_COMMAND`: /ytdl
  - `GYTDL_COMMAND`: /gytdl
  - `PYTDL_COMMAND`: /pytdl
  - `GLEECH_COMMAND`: /gleech
  - `TELEGRAM_LEECH_COMMAND`: /tleech
  - `TELEGRAM_LEECH_UNZIP_COMMAND`: /textract
  - `CLONE_COMMAND_G`:/gclone
  - `UPLOAD_COMMAND`: /upload
  - `RENEWME_COMMAND` : /leech command.
  - `SAVE_THUMBNAIL`: /savethumb
  - `CLEAR_THUMBNAIL`: /clearthumb
  - `GET_SIZE_G`: /clearthumb
  - `TOGGLE_VID`: /togglevid
  - `TOGGLE_DOC`: /toggledoc
  - `RENAME_COMMAND`: /rename
  - `CANCEL_COMMAND_G`: /cancel
  - `MAX_FILE_SIZE`:
  - `TG_MAX_FILE_SIZE`:
  - `FREE_USER_MAX_FILE_SIZE`
  - `MAX_TG_SPLIT_FILE_SIZE`:
  - `CHUNK_SIZE`:
  - `MAX_MESSAGE_LENGTH`:
  - `PROCESS_MAX_TIMEOUT`:
  - `ARIA_TWO_STARTED_PORT`:
  - `EDIT_SLEEP_TIME_OUT`:
  - `MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START`:
  - `FINISHED_PROGRESS_STR`:
  - `UN_FINISHED_PROGRESS_STR`:
  - `TG_OFFENSIVE_API`:
  - `CUSTOM_FILE_NAME`:
  - `UPLOAD_AS_DOC`: Takes two option True or False. If True file will be uploaded as document. This is for people who wants video files as document instead of streamable.
  - `INDEX_LINK`: (Without `/` at last of the link, otherwise u will get error) During creating index, plz fill `Default Root ID` with the id of your `DESTINATION_FOLDER` after creating. Otherwise index will not work properly.
  - `DESTINATION_FOLDER`: Name of your folder in your respective drive where you want to upload the files using the bot.
