python3 -m tgtlg
 
  - `TG_BOT_TOKEN`: 1948841770:AAGX5_t7-q0uodiq_U3XwI2qV7d80LFDASA
  - `APP_ID` 3495663
  - `API_HASH`: bd2c2a8c9fa3169038cdf3c9c8215f19
  - `AUTH_CHANNEL`: -1001585071628
  - `OWNER_ID`: 1874954413
  - `CLONE_COMMAND_G`: /gclone@Leech96bot
  - `UPLOAD_COMMAND`: /upload@Leech96bot
  - `RENEWME_COMMAND`: /leech@Leech96bot
  - `SAVE_THUMBNAIL`: /savethumb@Leech96bot
  - `CLEAR_THUMBNAIL`: /clearthumb@Leech96bot
  - `GET_SIZE_G`: /clearthumb@Leech96bot
  - `TOGGLE_VID`: /togglevid@Leech96bot
  - `TOGGLE_DOC`: /toggledoc@Leech96bot
  - `RENAME_COMMAND`: /rename@Leech96bot
  - `CANCEL_COMMAND_G`: /cancel@Leech96bot

  - `MAX_FILE_SIZE`:
  - `TG_MAX_FILE_SIZE`:
  - `FREE_USER_MAX_FILE_SIZE`
  - `MAX_TG_SPLIT_FILE_SIZE`:
  - `CHUNK_SIZE`:
  - `MAX_MESSAGE_LENGTH`:
  - `PROCESS_MAX_TIMEOUT`:
  - `ARIA_TWO_STARTED_PORT`:
  - `EDIT_SLEEP_TIME_OUT`:
  - `MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START`:
  - `FINISHED_PROGRESS_STR`:
  - `UN_FINISHED_PROGRESS_STR`:
  - `TG_OFFENSIVE_API`:
  - `CUSTOM_FILE_NAME`:
  - `UPLOAD_AS_DOC`: /upload_as_doc@Leech96bot
  - `INDEX_LINK`: 
  - `DESTINATION_FOLDER`: 
  - `/rclone`:
  - `/gclone`: /gclone@Leech96bot
  - `/help`: /help@Leech96bot
  - `/leech`: /leech@Leech96bot
  - `/archive`: /archive@Leech96bot
  - `/extract`: /extract@Leech96bot
  - `/gleech`: /gleech@Leech96bot
  - `/garchive`: /garchive@Leech96bot
  - `/gextract`: /gextract@Leech96bot
  - `/gclone`: gclone@Leech96bot
  - `/tleech`: /tleech@Leech96bot
  - `/textract`: /textract@Leech96bot
  - `/ytdl`: /ytdl@Leech96bot
  - `/pytdl`: /pytdl@Leech96bot
  - `/gytdl`: /gytdl@Leech96bot
  - `/gpytdl`: /gpytdl@Leech96bot
  - `/getsize`: /getzize@Leech96bot
  - `/renewme`: /renewme@Leech96bot
  - `/rename`: /rename@Leech96bot
  - `/rclone`: 
  - `/log`: /log@Leech96bot
  - [GautamKumar](https://github.com/gautamajay52/TorrentLeech-Gdrive)
  - [SpEcHiDe](https://github.com/SpEcHiDe/PublicLeech) for his wonderful code
  - [cihanvol](https://github.com/cihanvol) for [direct_link_generator](https://github.com/reaitten/tgtlg/blob/main/tgtlg/helper_funcs/direct_link_generator.py)
  - [MaxxRider](https://github.com/MaxxRider) for tweaked version of [TorrentLeech-Gdrive](https://github.com/MaxxRider/Leech-Pro)
  - [Rclone Team](https://rclone.org) for theirs awesome tool
  - [Dan Tès](https://telegram.dog/haskell) for his [Pyrogram Library](https://github.com/pyrogram/pyrogram)
  - [Robots](https://telegram.dog/Robots) for their [@UploadBot](https://telegram.dog/UploadBot)
  - [@AjeeshNair](https://telegram.dog/AjeeshNait) for his [torrent.ajee.sh](https://torrent.ajee.sh)
  - [@gotstc](https://telegram.dog/gotstc), @aryanvikash, [@HasibulKabir](https://telegram.dog/HasibulKabir) for their TORRENT groups

