name: Docker Build CI

on:
  workflow_dispatch:


jobs:
  Docker Build CI:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
       echo "${{ secrets.DOCKERPASS }}" | docker login -u "${{ secrets.DOCKERUSER }}" --password-stdin
       docker build -t debosama10/tk:latest .
       docker push debosama10/tk:latest
